version: '3'
services:
    laravel:
        build:
            context: ./laravel/vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '.'
        volumes:
            - './laravel:/var/www/html'
        networks:
            - sail
        depends_on:
            - postgres
            - next
    postgres:
        image: 'postgres:latest'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_DB: '${DB_DATABASE}'
        volumes:
            - 'sail-postgres:/var/lib/postgresql/data'
            - './laravel/vendor/laravel/sail/database/pgsql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD-SHELL
                - pg_isready
            retries: 3
            timeout: 5s
    next:
        image: 'node:latest'
        ports:
            - '${FORWARD_NEXT_PORT:-3000}:3000'
        working_dir: '/usr/src/app'
        volumes:
            - ./nextjs:/usr/src/app
            - sail-next:/usr/src/app/node_modules
        networks:
            - sail
        command: 'bash -c "npm i && npm run dev"'
        stop_grace_period: 3s
        healthcheck:
            test:
                - CMD
                - curl
                - '--fail'
                - 'http://localhost:3000'
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sail-postgres:
        driver: local
    sail-next:
        driver: local
